server:
  port: 8085
spring:
  application:
    name: "crediya-solicitudes-ms"
  devtools:
    add-properties: false
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/crediya-autenticacion-ms_db
    username: rubenbarrios
    password:
#    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://postgres-auth:5432/crediya-solicitudes-ms}
#    username: ${SPRING_R2DBC_USERNAME:root}
#    password: ${SPRING_R2DBC_PASSWORD:password}
  sql:
    init:
      mode: always
    data:
      r2dbc:
        repositories:
          enabled: true
adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: crediya-solicitudes-ms_db
    schema: public
    username: rubenbarrios
    password:

#adapters:
#    r2dbc:
#      host: localhost
#      port: 5432
#      database: Authentication
#      schema: public
#      username: postgres
#      password: 30052630

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

jwt:
  secret: "mysuperlongsecretkeythatismorethan32bytes123!"
  expiration: 3600000